export const SITE_MAP = [
  // MAIN NAVIGATION
  "https://www.gmraerocity.com/",
  "https://www.gmraerocity.com/about",
  "https://www.gmraerocity.com/events",
  "https://www.gmraerocity.com/contactus",
  "https://www.gmraerocity.com/faq",
  "https://www.gmraerocity.com/privacy-policy",
  
  // MEDIA
  "https://www.gmraerocity.com/e-magazine",
  "https://gmraerocity.com/magazine/march-april-2026/",
  "https://www.gmraerocity.com/blog",
  
  // FACILITIES
  "https://gmraerocity.inxp.in/tours",
  "https://www.gmraerocity.com/concierge",
  "https://www.gmraerocity.com/shuttle",
  "https://www.gmraerocity.com/ipsaa",
  "https://www.gmraerocity.com/delhi-to-agra-bus-service",
  "https://www.gmraerocity.com/parking",
  
  // AEROCITY ONE
  "https://www.gmraerocity.com/aerocityone",
  
  // THE SQUARE
  "https://www.gmraerocity.com/the-square",
  "https://www.gmraerocity.com/offers",
  "https://www.gmraerocity.com/blue-tokai",
  "https://www.gmraerocity.com/chai-point",
  "https://www.gmraerocity.com/chique",
  "https://www.gmraerocity.com/grovers-bespoke",
  "https://www.gmraerocity.com/icici-bank",
  "https://www.gmraerocity.com/kama-ayurveda",
  "https://www.gmraerocity.com/looks-prive",
  "https://www.gmraerocity.com/manan",
  "https://www.gmraerocity.com/minaki",
  "https://www.gmraerocity.com/modern-bazaar",
  "https://www.gmraerocity.com/nicobar",
  "https://www.gmraerocity.com/ruvido",
  "https://www.gmraerocity.com/sugar-and-spice",
  "https://www.gmraerocity.com/utsav",
  
  // WORK
  "https://www.gmraerocity.com/work",
  "https://www.gmraerocity.com/work/offices",
  "https://www.gmraerocity.com/work/meeting-room",
  "https://www.gmraerocity.com/work/coworking",
  "https://www.gmraerocity.com/aloft-commercial-tower",
  "https://www.gmraerocity.com/andaz-commercial-tower",
  "https://www.gmraerocity.com/aria-jw-marriott",
  "https://www.gmraerocity.com/caddie-commercial-tower",
  "https://www.gmraerocity.com/world-mark",
  
  // STAY
  "https://www.gmraerocity.com/stay",
  "https://www.gmraerocity.com/aloft",
  "https://www.gmraerocity.com/andaz",
  "https://www.gmraerocity.com/holiday-inn",
  "https://www.gmraerocity.com/ibis",
  "https://www.gmraerocity.com/jw-marriott-hotel",
  "https://www.gmraerocity.com/lemon-tree-premier-hotel/",
  "https://www.gmraerocity.com/novotel",
  "https://www.gmraerocity.com/pride-plaza/",
  "https://www.gmraerocity.com/pullman-hotel",
  "https://www.gmraerocity.com/roseate-house-hotel/",
  
  // EAT & DRINK
  "https://www.gmraerocity.com/eat-drink",
  "https://gmraerocity.com/eat-drink/fine-dining",
  "https://www.gmraerocity.com/anna-maya-andaz/",
  "https://www.gmraerocity.com/aqua-grill-pride-plaza",
  "https://www.gmraerocity.com/burma-burma",
  "https://www.gmraerocity.com/cafe-pride-plaza",
  "https://www.gmraerocity.com/del-roseate-fine-dining",
  "https://www.gmraerocity.com/farmer-basket-at-pluck-pullman",
  "https://www.gmraerocity.com/honk-pullman",
  "https://www.gmraerocity.com/jw-lounge-jw-marriott",
  "https://www.gmraerocity.com/k3-jw-marriott",
  "https://www.gmraerocity.com/kampai",
  "https://www.gmraerocity.com/kheer-roseate",
  "https://www.gmraerocity.com/khubani",
  "https://www.gmraerocity.com/tara-roseate-rooftop-lounge",
  "https://www.gmraerocity.com/the-hangar-lounge-holiday-inn",
  "https://www.gmraerocity.com/the-nook-aloft",
  "https://www.gmraerocity.com/viva-all-day-dining-at-holiday-inn",
  
  "https://gmraerocity.com/eat-drink/casual-dining",
  "https://www.gmraerocity.com/cafe-pluck-pullman",
  "https://www.gmraerocity.com/citrus-cafe-at-lemon-tree",
  "https://www.gmraerocity.com/daryaganj",
  "https://gmraerocity.com/daryaganj-gold/",
  "https://www.gmraerocity.com/dhaba",
  "https://www.gmraerocity.com/food-exchange-novotel",
  "https://www.gmraerocity.com/kylin",
  "https://www.gmraerocity.com/mesa",
  "https://www.gmraerocity.com/monsoon-cafe-by-lota",
  "https://www.gmraerocity.com/nua-cafe",
  "https://www.gmraerocity.com/one-8-commune",
  "https://www.gmraerocity.com/punjab-grill",
  "https://www.gmraerocity.com/quoin-pullman",
  "https://www.gmraerocity.com/reve/",
  "https://www.gmraerocity.com/spice-it-ibis",
  "https://www.gmraerocity.com/stallion-pride-plaza",
  "https://www.gmraerocity.com/the-beer-cafe",
  "https://www.gmraerocity.com/toy-room",
  "https://www.gmraerocity.com/underdoggs",
  
  "https://gmraerocity.com/eat-drink/fast-food",
  "https://www.gmraerocity.com/food-capital",
  
  "https://gmraerocity.com/eat-drink/cafe",
  "https://www.gmraerocity.com/cafe-delhi-heights",
  "https://www.gmraerocity.com/chaayos",
  "https://www.gmraerocity.com/costa-coffee",
  "https://www.gmraerocity.com/delhi-baking-company",
  "https://www.gmraerocity.com/hazelnut-factory",
  "https://www.gmraerocity.com/pret-a-manger",
  "https://www.gmraerocity.com/roasted-by-roseate",
  "https://www.gmraerocity.com/starbucks",
  
  "https://gmraerocity.com/eat-drink/bakery",
  "https://www.gmraerocity.com/airobakes",
  "https://www.gmraerocity.com/mr-confectioner-pride-plaza",
  "https://www.gmraerocity.com/refuel-aloft",
  
  "https://www.gmraerocity.com/eat-drink/food-court",
  
  // CUISINE CATEGORIES
  "https://www.gmraerocity.com/eat-drink/north-indian",
  "https://www.gmraerocity.com/eat-drink/modern-indian",
  "https://www.gmraerocity.com/eat-drink/mughlai",
  "https://www.gmraerocity.com/eat-drink/asian",
  "https://www.gmraerocity.com/eat-drink/japanese",
  "https://www.gmraerocity.com/eat-drink/chinese",
  "https://www.gmraerocity.com/eat-drink/italian",
  "https://www.gmraerocity.com/eat-drink/continental",
  "https://www.gmraerocity.com/eat-drink/european",
  "https://gmraerocity.com/eat-drink/lounge",
  
  // RETAIL
  "https://www.gmraerocity.com/retail",
  "https://www.gmraerocity.com/aptronix",
  "https://www.gmraerocity.com/bagline",
  "https://www.gmraerocity.com/da-milano",
  "https://www.gmraerocity.com/forest-essentials",
  "https://www.gmraerocity.com/geom365",
  "https://www.gmraerocity.com/luxury-retail-at-roseate-house",
  "https://www.gmraerocity.com/miniso",
  "https://www.gmraerocity.com/tesla",
  "https://www.gmraerocity.com/world-of-valaya-by-jj-valaya",
  
  // RELAX
  "https://www.gmraerocity.com/relax",
  "https://www.gmraerocity.com/aheli-spa-roseate",
  "https://www.gmraerocity.com/lea-spa-and-salon",
  "https://www.gmraerocity.com/the-wellness-spa-at-pullman",
  "https://www.gmraerocity.com/spa-by-jw",
  "https://www.gmraerocity.com/spa-andaz",
  "https://www.gmraerocity.com/zivaya-spa-at-aloft",
  "https://www.gmraerocity.com/zivaya-spa-at-pride-plaza",
  
  // BLOGS
  "https://www.gmraerocity.com/blog/designing-districts-connectivity-walkability-smart-infrastructure/",
  "https://www.gmraerocity.com/blog/shared-urban-spaces-making-comeback/",
  "https://www.gmraerocity.com/blog/when-cricket-meets-cuisine-the-unbeatable-community-spirit-of-gmr-aerocity/",
  "https://www.gmraerocity.com/blog/art-of-staying-in-why-staycation-works/",
  "https://www.gmraerocity.com/blog/morning-to-evening-self-care-gmr-aerocity/",
  "https://www.gmraerocity.com/blog/why-global-businesses-choose-airport-centric-cities/",
  
  // DELHI TOURISM
  "https://delhitourism.gov.in/",
  "https://delhitourism.gov.in/aboutus",
  "https://delhitourism.gov.in/tourist_place",
  "https://delhitourism.gov.in/transport",
  "https://delhitourism.gov.in/entertainment",
  "https://delhitourism.gov.in/ebooking",
  "https://delhitourism.gov.in/itinerary"
];
